/**
 * ==========================================================================
 * CoQuí: Correlated Quantum ínterface
 *
 * Copyright (c) 2022-2025 Simons Foundation & The CoQuí developer team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ==========================================================================
 */


#include <fstream>
#include <filesystem>

#include "configuration.hpp"
#include "IO/app_loggers.h"
#include "arch/arch.h"
#include "utilities/check.hpp"
#include "utilities/fortran_utilities.h"
#include "utilities/kpoint_utils.hpp"
#include "mpi3/environment.hpp"
#include "mpi3/communicator.hpp"
#include "h5/h5.hpp"
#include "nda/nda.hpp"
#include "nda/h5.hpp"
#include "nda/tensor.hpp"
#include "numerics/distributed_array/nda.hpp"
#include "numerics/shared_array/nda.hpp"
#include "utilities/qe_utilities.hpp"
#include "utilities/mpi_context.h"
#include "mean_field/MF.hpp"
#include "mean_field/distributed_orbital_readers.hpp"
#include "hamiltonian/add_vloc.hpp"
#include "hamiltonian/v_h.hpp"
#include "hamiltonian/v_x.hpp"
#include "hamiltonian/paw/v_h_paw.hpp"
#include "hamiltonian/paw/v_x_paw.hpp"
#include "hamiltonian/paw/paw_onecenter.hpp"   // compute_paw_deeq / compute_deeq_scf
#include "hamiltonian/pseudo/pseudopot.h"
#include "hamiltonian/pseudo/pseudopot_to_h5.hpp"
#include "numerics/nda_functions.hpp"

namespace hamilt 
{

using utils::mpi_context_t;
using math::shm::make_shared_array;
using boost::mpi3::communicator;
using boost::mpi3::shared_communicator;

template<typename MF_t>
pseudopot::pseudopot(MF_t &mf, std::string const filename) :
  mpi(mf.mpi()),
  fft_mesh_aug(mf.fft_grid_dim_aug()),  // dense grid: vsc, vloc, mill_g, all PAW augmentation pieces
  nnr_aug(mf.nnr_aug()),            // dense FFT box (must hold all dense G-vectors)
  recv(mf.recv()),
  lattv(mf.lattv()),
  nkpts(mf.nkpts()),
  nkpts_ibz(mf.nkpts_ibz()),
  kpts(mf.kpts()),
  kpts_crys(mf.kpts_crystal()),
  kp_to_ibz(mf.kp_to_ibz()),
  kp_trev(mf.kp_trev()),
  symm_list(mf.symm_list()),
  kp_symm(mf.kp_symm()),
  Pskna(make_shared_array<nda::array_view<ComplexType,4>>(*mpi,{1,1,1,1})),   // resize later
  Dnn(make_shared_array<nda::array_view<ComplexType,3>>(*mpi,{1,1,1})),       // resize later
  Dnn_atom_static(make_shared_array<nda::array_view<ComplexType,3>>(*mpi,{1,1,1})), // resized+filled in read_vnl_h5 for USPP/PAW
  swfc_to_rho(detail::make_wfc_to_rho(*mpi,mf,fft_mesh_aug)),
  svloc(make_shared_array<nda::array_view<ComplexType,3>>(*mpi,{1,1,1})),            // resize later
  svsc(make_shared_array<nda::array_view<ComplexType,3>>(*mpi,{1,1,1})),  // resize later
  qgm(make_shared_array<nda::array_view<ComplexType,3>>(*mpi,{1,1,1})),            // resize later
  qq_nt_data(make_shared_array<nda::array_view<ComplexType,3>>(*mpi,{1,1,1}))     // resize later
{
  // Cache cartesian atom positions for the v_h_paw augmentation step.
  // mf.atomic_positions() returns shape (nat, 3) in cartesian.
  {
    auto ap = mf.atomic_positions();
    atom_pos_cart = nda::array<double,2>::zeros({ap.extent(0), ap.extent(1)});
    atom_pos_cart() = ap;
  }
  if( mf.mf_type() == mf::pyscf_source ) { 

    // nothing to do, evaluation routines should not be called! 
    ptype = pp_FILE_t;
    return ;

  } else { 

    // remember input type
    input_file_type = mf.input_file_type();        

    app_log(2,"************************************************");
    app_log(2," Initializing External Potential: ");
    app_log(2,"************************************************");
#if defined(ENABLE_DEVICE)
    app_log(2,"  Device support enabled.");
#endif
    if(filename != "" or mf.input_file_type() == mf::h5_input_type) {
      input_file_name = (filename != ""?filename:mf.filename());
      utils::check(std::filesystem::exists(input_file_name), "Error: Missing file: {}",input_file_name);
      h5::file file;
      try {
        file = h5::file(input_file_name, 'r');
      } catch(...) {
        APP_ABORT("Failed to open h5 file: {}, mode:r",input_file_name);
      }
      h5::group grp(file);
      read_vnl_h5(mf,grp);
    } else if( mf.input_file_type() == mf::xml_input_type and mf.mf_type() == mf::qe_source ) {
      // read ASCII and binary files generated by QE::pp.x and QE::pw2bgw.x
      input_file_name = mf.outdir();
      read_vnl_pw2bgw(mf,mf.outdir());
    } else
      utils::check(false,"Error in pseudopot:: Unknown input file type/mf object combination.");

    double x = 16.0/1024.0/1024.0/1024.0;
    app_log(2,"\n Memory usage: ");
    app_log(2,"   Overlaps:                      {} MB",Pskna.local().size()*x);  
    app_log(2,"   Dion:                          {} MB",Dnn.local().size()*x);  
    if(ptype ==  pp_uspp_t)
      app_log(2,"   Augmentation Functions:        {} MB",qgm.local().size()*x);  
    if(ptype ==  pp_paw_t)
      app_log(2,"   Atomic terms:        {} MB",0);  
    app_log(2,"************************************************\n");

  } 
}

// MAM: pw2bgw only allows NCPP psp
template<typename MF_t>
void pseudopot::read_vnl_pw2bgw(MF_t &mf, std::string outdir) 
{
  utils::check(mf.npol()==1, "Error in read_vnl_pw2bgw: Noncollinear not yet supported.");
  std::string fname = outdir + "/VKB";
  decltype(nda::range::all) all;
  int sz = fname.size();
  int npwx,nkb,nat,nhm,nsp,ierr;
  auto wfc_g = mf.wfc_truncated_grid();
  long ngm = wfc_g->size();
  auto fft2gv = wfc_g->fft_to_gv();
  long wfc_nnr = wfc_g->nnr();
  if(mpi->comm.root()) {
    int nspin_,nk_; 
    utils::check(std::filesystem::exists(fname), "Error: Missing file: {}",fname); 
    FC_read_pw2bgw_vkbg_header(fname.c_str(), sz, nspin_, nkb, npwx, nk_, nat, nsp, nhm,ierr);
    utils::check(ierr==0, "Error reading QE::pw2bgw vkbg file (header info).");
    utils::check(mf.nkpts_ibz()==nk_,"pseudopot: Data mismatch.");
    utils::check(mf.nspin()==nspin_,"pseudopot: Data mismatch.");
    utils::check(ngm>=npwx,"pseudopot: Data mismatch.");

    app_log(2,"  input type: qe::pp/qe::pw2bgw");
    app_log(2,"  type: NCPP");
    app_log(2,"  # of species: {}",nsp);
    app_log(2,"  # of atoms: {}",nat);
    app_log(2,"  max # of projectors per atom: {}",nhm);
    app_log(2,"  # of projectors: {}",nkb);
  } 
  long nk = mf.nkpts_ibz();
  long nbnd = mf.nbnd();

  mpi->comm.broadcast_value(nkb);
  mpi->comm.broadcast_value(nat);
  mpi->comm.broadcast_value(nsp);
  mpi->comm.broadcast_value(nhm);
  mpi->comm.broadcast_value(npwx);

  ityp.resize(nat);
  nh.resize(nsp);
  nh()=0;
  ityp()=0;
   
  nda::array<int,1> npw(nk);
  sarray_t<nda::array_view<int,3>> miller(*mpi,{nk,npwx,3}); 
  sarray_t<nda::array_view<ComplexType,3>> vkb(*mpi,{nk,nkb,ngm}); 
  Dnn = sarray_t<nda::array_view<ComplexType,3>>(*mpi,{nsp,nhm,nhm}); 

  if(mpi->comm.root()) {
    int msz = int(nk*npwx*3), vsz=int(nk*nkb*npwx), Dsz = int(nspin*nsp*nhm*nhm);
    int k0=0, k1=nk;
    nda::array<double,4> Dnn_r(nspin,nsp,nhm,nhm); 
    if(npwx != ngm) {
      nda::array<ComplexType,3> vkb_r(nk,nkb,npwx);
      FC_read_pw2bgw_vkbg(fname.c_str(), sz, k0, k1, ityp.data(), nat, 
        nh.data(), nsp, npw.data(), nk, 
        Dnn_r.data(), Dsz, miller.local().data(), msz, vkb_r.data(), vsz, ierr);
      vkb.local()(all,all,nda::range(npwx)) = vkb_r();
    } else {
      FC_read_pw2bgw_vkbg(fname.c_str(), sz, k0, k1, ityp.data(), nat, 
        nh.data(), nsp, npw.data(), nk, 
        Dnn_r.data(), Dsz, miller.local().data(), msz, vkb.local().data(), vsz, ierr);
    }
    // modify in non-collinear case
    for(int i=0; i<nsp; i++)
      Dnn.local()(i,nda::range(nh(i)),nda::range(nh(i))) = Dnn_r(0,i,nda::range(nh(i)),nda::range(nh(i)));
    // to Hartree
    nda::tensor::scale(ComplexType(0.5),Dnn.local());
    utils::check(ierr==0, "Error reading QE::pw2bgw vkbg file (arrays) - ierr:{}",ierr);
  }

  mpi->comm.broadcast_n(npw.data(),nk);
  mpi->comm.broadcast_n(ityp.data(),nat);
  mpi->comm.broadcast_n(nh.data(),nsp);
  
  if(mpi->node_comm.root()) {
    mpi->internode_comm.broadcast_n(miller.local().data(),miller.size());
    mpi->internode_comm.broadcast_n(vkb.local().data(),vkb.size());
    mpi->internode_comm.broadcast_n(Dnn.local().data(),Dnn.size());
  }
  mpi->comm.barrier();

  // mapping from miller indices to wfc_g
  sarray_t<nda::array_view<long,2>> sk2g(*mpi,{nk,npwx});
  auto k2g = sk2g.local();  
  auto miller_loc = miller.local();

  int rank = mpi->comm.rank();
  int np = mpi->comm.size();
  // setup index mappings
  { 
    long NX = wfc_g->mesh(0), NY = wfc_g->mesh(1), NZ = wfc_g->mesh(2);
    for( int ik=0; ik<nk; ik++ ) {
      if(  ik%np != rank ) continue;
      auto mill = miller_loc(ik,nda::range(npw(ik)),all);
      // map miller index to wfc_g truncated grid
      for( int i=0; i<npw(ik); i++ ) {
        long n1 = mill(i,0); if(n1<0) n1 += NX;
        long n2 = mill(i,1); if(n2<0) n2 += NY;
        long n3 = mill(i,2); if(n3<0) n3 += NZ;
        utils::check(n1 < NX, "read_vnl_pw2bgw: Index out of range. i:{}, n:{}, NX:{}",i,n1,NX);
        utils::check(n2 < NY, "read_vnl_pw2bgw: Index out of range. i:{}, n:{}, NY:{}",i,n2,NY);
        utils::check(n3 < NZ, "read_vnl_pw2bgw: Index out of range. i:{}, n:{}, NZ:{}",i,n3,NZ);
        long N = (n1*NY + n2)*NZ + n3;
        utils::check( N >= 0 and N < wfc_nnr, "read_vnl_pw2bgw: Index out of range. N:{}, nnr:{}",N,wfc_nnr);
        k2g(ik,i) = fft2gv(N);  
        utils::check( k2g(ik,i) >= 0 and k2g(ik,i) < ngm, "read_vnl_xml: Index not mapped in truncated grid. ");
      }
    }
    mpi->comm.barrier();
    if(mpi->node_comm.root()) 
      mpi->internode_comm.all_reduce_in_place_n(k2g.data(),k2g.size(),std::plus<>{});
    mpi->comm.barrier();
  }
  miller = sarray_t<nda::array_view<int,3>>(*mpi,{1,1,1}); 

  // setup offset list
  ofs.resize(nat);
  long iofs=0;
  for( auto [i,n] : itertools::enumerate(nh) )
    for( auto iat : nda::range(nat) )
      if(ityp(iat) == i) {
        ofs(iat) = iofs;
        iofs += n;  
      }

  // calculate projectors
  Pskna = sarray_t<nda::array_view<ComplexType,4>>(*mpi,{nspin,nk,npol*long(nkb),nbnd}); 
  auto Ploc = Pskna.local();
  auto vkloc = vkb.local();  // MAM: vkb was conjugated above !!!
  nda::array<ComplexType,2> Orb(8,wfc_nnr);
  nda::array<ComplexType,2> buff(nkb,wfc_nnr);
  long iskb = 0;
  for( int is = 0; is < nspin; ++is ) 
    for( int ik = 0; ik < nk; ++ik )  
      for( int ib = 0; ib < nbnd; ib+=8, ++iskb ) { 
        if( iskb%np != rank ) continue; 
        int nb_ = std::min(8,int(nbnd)-ib);
        // (n,a) = conj[ (n,G) ] * T(a,G)
        mf.get_orbital_set('w', is, ik, nda::range(ib,ib+nb_), Orb(nda::range(nb_),all)); 
        buff() = ComplexType(0.0);
        for( auto [in,n] : itertools::enumerate(k2g(ik,nda::range(npw(ik)))) )
          buff(all,n) = nda::conj(vkloc(ik,all,in));
        nda::blas::gemm(ComplexType(1.0),buff, nda::transpose(Orb(nda::range(nb_),all)),
                        ComplexType(0.0),Ploc(is,ik,all,nda::range(ib,ib+nb_)));  
      }
  mpi->comm.barrier();
  if(mpi->node_comm.root()) {
    mpi->internode_comm.all_reduce_in_place_n(Ploc.data(),Ploc.size(),std::plus<>{});
  }
  mpi->comm.barrier();

  // local and self-consistent potentials
  spinorbit_loc = false;
  svloc = sarray_t<nda::array_view<ComplexType,3>>(*mpi,{nspin,1,nnr_aug});
  svsc = sarray_t<nda::array_view<ComplexType,3>>(*mpi,{nspin,npol*npol,nnr_aug});
  if(mpi->comm.root()) {
    if(std::filesystem::exists(outdir+"/VSC")) {
      nda::array<ComplexType,1> v;
      utils::read_qe_plot_file(1,outdir+"/VSC",mf.fft_grid_dim_aug(),v);  // V_eff is on dfftp
      // MAM: transform to nnr_aug grid...  spin/polarization dependence???
      // this is wrong if nspin or npol > 1!
      // ignore for now since this is not used anywhere!
      utils::check(v.extent(0) == nnr_aug, "Error: Dimension mismatch");
      for(int is=0; is<nspin; is++)
        svsc.local()(is,0,all) = v();
      // to Hartree
      nda::tensor::scale(ComplexType(0.5),svsc.local());
    } else {
// MAM: no direct evaluation of Fock matrix, so message is irrelevant. Reenable is direct evaluation is 
//      implemented, and only message if call is made, since it is rare to do this.
//      app_warning(stars+" Missing VSC file!!! Direct evaluation of Fock matrix will be incorrect!"+stars);
    }
    if(std::filesystem::exists(outdir+"/VLTOT")) { 
      nda::array<ComplexType,1> v;
      utils::read_qe_plot_file(2,outdir+"/VLTOT",mf.fft_grid_dim_aug(),v);  // V_loc is on dfftp
      // MAM: transform to nnr_aug grid...
      utils::check(v.extent(0) == nnr_aug, "Error: Dimension mismatch");
      for(int is=0; is<nspin; is++)
        svloc.local()(is,0,all) = v();
      // to Hartree
      nda::tensor::scale(ComplexType(0.5),svloc.local());
    } else {
#if defined(ALLOW_MISSING_VLTOT)
      app_warning("*************************************************************************");
      app_warning("*************************************************************************");
      app_warning("*************************************************************************");
      app_warning("  Missing VLTOT file!!! Non-interacting Hamiltonian could be incorrect!!!");
      app_warning("*************************************************************************");
      app_warning("*************************************************************************");
      app_warning("*************************************************************************");
#else
      APP_ABORT("Missing VLTOT file!!! Should exist in outdir:{}");
#endif
    }
  }

  if(mpi->node_comm.root()) {
    mpi->internode_comm.broadcast_n(svsc.local().data(),svsc.size());
    mpi->internode_comm.broadcast_n(svloc.local().data(),svloc.size());
  }
  mpi->comm.barrier();

}

template<typename MF_t>
void pseudopot::read_vnl_h5(MF_t &mf, h5::group& grp0)
{
  using nda::range;
  decltype(range::all) all;
  std::string type("");

  h5::group grp1 = grp0.open_group("Hamiltonian");
  h5::h5_read_attribute(grp1, "pp_type", type);

  app_log(2,"  input type: coqui::h5");
  if(type == "ncpp") {
    ptype = pp_ncpp_t;
    app_log(2,"  type: NCPP");
  } else if(type == "uspp") {
    ptype = pp_uspp_t;
    app_log(2,"  type: USPP");
  } else if(type == "paw") {
    ptype = pp_paw_t;
    app_log(2,"  type: PAW");
  } else {
    APP_ABORT("Invalid pp_type: {}",type);
  }

  h5::group grp = grp1.open_group(type);

  int nk, npwx;
  h5::h5_read_attribute(grp,"number_of_nspins",nspin);
  h5::h5_read_attribute(grp,"number_of_polarizations",npol);
  h5::h5_read_attribute(grp,"number_of_kpoints",nk);
  h5::h5_read_attribute(grp,"max_npw",npwx);
  int lspinorb;
  h5::h5_read_attribute(grp,"lspinorbit_nl",lspinorb);
  spinorbit_nl = (lspinorb!=0);
  h5::h5_read_attribute(grp,"lspinorbit_loc",lspinorb);
  spinorbit_loc = (lspinorb!=0);

  utils::check(nspin == mf.nspin(), "Error in pseudopot::read_vnl_h5: Inconsistent nspin.");
  utils::check(npol == mf.npol(), "Error in pseudopot::read_vnl_h5: Inconsistent npol:{} (mf:{})",npol,mf.npol());
  utils::check(nk == mf.nkpts_ibz(), "Error in pseudopot::read_vnl_h5: Inconsistent nkpts.");
  utils::check(mf.wfc_truncated_grid()->size() >= npwx,
               "Error in pseudopot::read_vnl_h5: ngm < max_npw");
  utils::check(spinorbit_nl == mf.spinorbit(), "Error in pseudopot::read_vnl_h5: Inconsistent spinorbit.");

  int nat, nsp, nkb, nhm;
  h5::h5_read_attribute(grp,"number_of_atoms",nat);
  h5::h5_read_attribute(grp,"number_of_species",nsp);
  h5::h5_read_attribute(grp,"total_num_of_proj",nkb);
  h5::h5_read_attribute(grp,"max_proj_per_atom",nhm);

  app_log(2,"  # of species: {}",nsp);
  app_log(2,"  # of atoms: {}",nat);
  app_log(2,"  max # of projectors per atom: {}",nhm);
  app_log(2,"  # of projectors: {}",nkb);
  app_log(2,"  # of polarizations: {}",npol);
  app_log(2,"  spin orbit: {}",spinorbit_nl);

  int nbnd = mf.nbnd();
  int rank = mpi->comm.rank();
  int np = mpi->comm.size();
  nda::array<int,1> npw(nk);

  // node number 
  int inode;
  if( mpi->node_comm.root() ) inode = mpi->internode_comm.rank();
  mpi->node_comm.broadcast_n(&inode,1,0);
  int nnodes = inode+1; 
  mpi->comm.all_reduce_in_place_n(&nnodes,1,mpi3::max<>{});

  // local potential
  svloc = sarray_t<nda::array_view<ComplexType,3>>(*mpi,{nspin,(spinorbit_loc?npol*npol:1),nnr_aug});
  svsc = sarray_t<nda::array_view<ComplexType,3>>(*mpi,{nspin,npol*npol,nnr_aug});
  if(mpi->comm.root()) {
    int ngm;
    h5::h5_read_attribute(grp,"ngm",ngm);
    // Cache the dense-grid size on the member here so the USPP/PAW broadcast
    // block below propagates the correct value to non-root ranks (otherwise
    // ngm_dense stayed 0 on root and the subsequent miller_g_dense broadcast
    // had a count mismatch under MPI > 1).
    ngm_dense = ngm;
    nda::array<long,1> k2g(ngm);

    {
      nda::array<int,2> mill_g(ngm,3);
      nda::h5_read(grp,"miller_g",mill_g);
      // mill_g lists dense G-vectors (ngm = ngm_dense), so the target FFT box
      // must be the dense (dfftp / aug) mesh — not the smooth one.
      utils::generate_k2g(mill_g,k2g,mf.fft_grid_dim_aug());
      // Cache miller_g_dense for v_h_paw augmentation. Only meaningful for
      // USPP/PAW; populated unconditionally here (cheap and harmless).
      miller_g_dense = mill_g;
    }


    // vsc
    { 
      auto vr = svsc.local();
      auto vr2d = nda::reshape(vr,std::array<long,2>{nspin*npol*npol,nnr_aug});
      auto v4D = nda::reshape(vr,std::array<long,4>{nspin*npol*npol,fft_mesh_aug(0),fft_mesh_aug(1),fft_mesh_aug(2)});
      math::nda::fft<true> F(v4D);

      nda::array<ComplexType,3> vl(nspin, npol*npol, ngm); 
      auto vl2d = nda::reshape(vl,std::array<long,2>{nspin*npol*npol,ngm});
      nda::h5_read(grp,"scf_local_potential",vl); 
      utils::check(vl.shape() == std::array<long,3>{nspin,npol*npol,ngm}, "Shape mismatch: scf_local_potential");
      vr() = ComplexType(0.0);
      nda::copy_select(true,1,k2g,ComplexType(1.0),vl2d,ComplexType(0.0),vr2d);
      F.backward(v4D);
    } 
 
    // vloc
    if(spinorbit_loc) {
      auto vr = svloc.local();
      auto vr2d = nda::reshape(vr,std::array<long,2>{nspin*npol*npol,nnr_aug});
      auto v4D = nda::reshape(vr,std::array<long,4>{nspin*npol*npol,fft_mesh_aug(0),fft_mesh_aug(1),fft_mesh_aug(2)});
      math::nda::fft<true> F(v4D);

      nda::array<ComplexType,3> vl(nspin, npol*npol, ngm); 
      auto vl2d = nda::reshape(vl,std::array<long,2>{nspin*npol*npol,ngm});
      vl() =  ComplexType(0.0);
      nda::h5_read(grp,"pp_local_component_nc",vl);
      utils::check(vl.shape() == std::array<long,3>{nspin,npol*npol,ngm}, 
                   "Shape mismatch: pp_local_component");
      vr() = ComplexType(0.0);
      nda::copy_select(true,1,k2g,ComplexType(1.0),vl2d,ComplexType(0.0),vr2d); 
      F.backward(v4D);
    } else {
      auto vr = svloc.local();
      auto vr2d = nda::reshape(vr,std::array<long,2>{nspin,nnr_aug});
      auto v4D = nda::reshape(vr,std::array<long,4>{nspin, fft_mesh_aug(0),fft_mesh_aug(1),fft_mesh_aug(2)});
      math::nda::fft<true> F(v4D);

      nda::array<ComplexType,1> vl_(ngm); 
      nda::h5_read(grp,"pp_local_component",vl_);
      utils::check(vl_.shape() == std::array<long,1>{ngm}, "Shape mismatch: pp_local_component");
      vr() = ComplexType(0.0);
      nda::copy_select(true,k2g,ComplexType(1.0),vl_,ComplexType(0.0),vr2d(0,all));
      for(int is=1; is<nspin; is++)
        vr(is, 0, all) = vr(0, 0, all);
      F.backward(v4D);
    }

    // to Hartree unit
    nda::tensor::scale(ComplexType(0.5),svsc.local());
    nda::tensor::scale(ComplexType(0.5),svloc.local());
  }
  if(mpi->node_comm.root()) { 
    mpi->internode_comm.broadcast_n(svsc.local().data(),svsc.size(),0);
    mpi->internode_comm.broadcast_n(svloc.local().data(),svloc.size(),0);
  }
  mpi->comm.barrier();

  // miller_g_dense was populated only on mpi.comm.root above; replicate.
  {
    int ngm_attr = (int)ngm_dense;
    if (ptype == pp_uspp_t || ptype == pp_paw_t) {
      // ngm_dense was set on root inside the uspp/paw branch above
      mpi->comm.broadcast_value(ngm_attr);
      ngm_dense = ngm_attr;
      if (!mpi->comm.root())
        miller_g_dense = nda::array<int,2>::zeros({ngm_dense, 3});
      mpi->comm.broadcast_n(miller_g_dense.data(), miller_g_dense.size(), 0);
    }
  }

  nh.resize(nsp);
  ityp.resize(nat);
  ofs.resize(nat);
  nda::h5_read(grp,"proj_per_atom",nh);
  nda::h5_read(grp,"projector_offset",ofs);
  nda::h5_read(grp,"npw",npw);
  nda::h5_read(grp,"atomic_id",ityp);
  //ityp = ityp-1;  
  // MAM: temporary fix until new pw2coqui.f90 is in place, remove eventually
  // should be 0-based indexing always
  {
    int id_min = *std::min_element(ityp.begin(),ityp.end());
    utils::check(id_min==0 or id_min==1,
                 "qe_interface::read_h5 Invalid atomic_ids array: min id:{}.",id_min);
    ityp() -= id_min;
  }

  // Dnn = dvan
  Dnn = sarray_t<nda::array_view<ComplexType,3>>(*mpi,{nsp,nhm*npol,nhm*npol});
  mpi->node_comm.barrier();

  // dion / dion_so is written by pw2coqui for ncpp, uspp, and paw alike.
  // The augmentation-related fields (qq_nt, ijtoh, augmentation_function_isp*)
  // are only present for uspp and paw and are read in the block below.
  if(mpi->node_comm.root())
  {
    if(spinorbit_nl) {
      nda::array<ComplexType,4> Dnn_c(nsp,npol*npol,nhm,nhm);
      nda::h5_read(grp,"dion_so",Dnn_c);
      auto Dloc = Dnn.local();
      // dion_so was written in column-major; reorder.
      for( int s=0; s<nsp; ++s )
        for( int p=0; p<npol; ++p )
          for( int q=0; q<npol; ++q )
            for( int n=0; n<nhm; ++n )
              for( int m=0; m<nhm; ++m )
                Dloc(s,n*npol+p,m*npol+q) = Dnn_c(s,p*npol+q,m,n);
    } else {
      nda::array<double,3> Dnn_r(nsp,nhm,nhm);
      nda::h5_read(grp,"dion",Dnn_r);
      auto Dloc = Dnn.local();
      Dloc() = ComplexType(0.0);
      for( int s=0; s<nsp; ++s )
        for( int p=0; p<npol; ++p )
          for( int n=0; n<nhm; ++n )
            for( int m=0; m<nhm; ++m )
              Dloc(s,n*npol+p,m*npol+p) = Dnn_r(s,n,m);
    }
    nda::tensor::scale(ComplexType(0.5),Dnn.local());
  }
  mpi->node_comm.barrier();

  // NOTE (plan A1): QE `deeq` is no longer read — it carries QE's converged
  // V_H and V_xc content and violates the no-XC static-D contract (plan F1).
  // The per-atom static tensor Dnn_atom_static (dion replica + ex_cvij) is
  // assembled after the paw_species fields are loaded below; the
  // density-dependent Hartree-only terms are rebuilt per evaluation via
  // compute_paw_deeq (plan I2/I3).

  // USPP / PAW augmentation overlap and Q^IJ(G).
  // qq_nt: per-species ⟨β|Q|β⟩ overlap, shape (nsp, nhm, nhm) on disk.
  // ijtoh: composite (ih,jh) -> ij map, shape (nsp, nhm, nhm), 1-based.
  // augmentation_function_isp{nt}: Q^IJ(G) on the dense grid, complex,
  //   shape (nij(nt), ngm_dense) per species, no structure factor.
  // For non-collinear/SOC USPP we'd also need qq_so; not implemented here
  // yet (will warn).
  qq_nt_data = sarray_t<nda::array_view<ComplexType,3>>(*mpi,
                  {std::max(1L,(long)nsp), std::max(1L,(long)nhm),
                   std::max(1L,(long)nhm)});
  if(ptype == pp_uspp_t or ptype == pp_paw_t) {
    int ngm_attr = 0;
    h5::h5_read_attribute(grp,"ngm",ngm_attr);
    ngm_dense = ngm_attr;
    long nij_max = static_cast<long>(nhm)*(nhm+1)/2;
    qgm = sarray_t<nda::array_view<ComplexType,3>>(*mpi,
            {(long)nsp, std::max(1L,nij_max), ngm_dense});
    ijtoh = nda::array<int,3>::zeros({nsp, nhm, nhm});

    if(mpi->node_comm.root()) {
      // ijtoh is integer, written as h5_write_tensor_int(ijtoh, "ijtoh") in
      // pw2coqui. Fortran (nhm, nhm, nsp) -> C++ (nsp, nhm, nhm).
      nda::h5_read(grp,"ijtoh",ijtoh);

      // qq_nt: real on disk for non-SOC. SOC path (qq_so) is a TODO.
      if(spinorbit_nl) {
        app_warning("USPP/PAW + spin-orbit: qq_so reader not yet wired; "
                    "augmentation overlap will be set to zero.");
        qq_nt_data.local()() = ComplexType(0.0);
      } else {
        nda::array<double,3> qq_r(nsp, nhm, nhm);
        qq_r() = 0.0;
        try { nda::h5_read(grp,"qq_nt",qq_r); }
        catch(...) {
          app_warning("USPP/PAW: 'qq_nt' missing from h5 file. "
                      "Re-run pw2coqui with the latest schema. "
                      "Continuing with zero augmentation overlap.");
        }
        auto Qloc = qq_nt_data.local();
        Qloc() = ComplexType(0.0);
        for(int s=0; s<nsp; ++s)
          for(int n=0; n<nhm; ++n)
            for(int m=0; m<nhm; ++m)
              Qloc(s,n,m) = ComplexType(qq_r(s,n,m), 0.0);
      }

      // Q^IJ(G) per species. Each species has nij(nt) = nh(nt)*(nh(nt)+1)/2
      // pairs; pad to nij_max with zeros in qgm.
      auto qg_loc = qgm.local();
      qg_loc() = ComplexType(0.0);
      for(int nt=0; nt<nsp; ++nt) {
        long nij = static_cast<long>(nh(nt))*(nh(nt)+1)/2;
        if(nij <= 0) continue;
        std::string ds = "augmentation_function_isp"+std::to_string(nt);
        try {
          nda::array<ComplexType,2> qfn(nij, ngm_dense);
          nda::h5_read(grp,ds,qfn);
          qg_loc(nt, nda::range(nij), nda::range(ngm_dense)) = qfn;
        } catch(...) {
          app_warning("USPP/PAW: missing dataset '{}' in h5 file. "
                      "Augmentation Q^IJ(G) for species {} set to zero.",
                      ds, nt);
        }
      }
    }
  }
  if(mpi->node_comm.root()) { /* no-op: already on root */ }
  mpi->node_comm.barrier();
  if(mpi->node_comm.root()) {
    if(qgm.local().size() > 0)
      mpi->internode_comm.broadcast_n(qgm.local().data(), qgm.size(), 0);
    if(qq_nt_data.local().size() > 0)
      mpi->internode_comm.broadcast_n(qq_nt_data.local().data(),
                                      qq_nt_data.size(), 0);
  }
  if(ijtoh.size() > 0)
    mpi->comm.broadcast_n(ijtoh.data(), ijtoh.size(), 0);
  mpi->comm.barrier();

  // Per-species PAW radial data (filled when /Hamiltonian/Species/ exists
  // in the h5 file), including Onecenter/deltaC for PAW species.
  // The five heavy radial tables (aewfc, pswfc, qfuncl, deltaC, core_aewfc)
  // are loaded on global root into per-species temporaries, then placed in
  // node-shared memory (paw_species_shm) and exposed to consumers as
  // `nda::array_view` fields of species_paw_t — one node-local copy
  // instead of a per-rank replication that scaled to ~3 GB/species on a
  // 96-core node.
  paw_species.clear();
  paw_species_shm.clear();
  if(ptype == pp_uspp_t or ptype == pp_paw_t) {
    paw_species.resize(nsp);
    paw_species_shm.reserve(nsp);
    for (int nt = 0; nt < nsp; ++nt) paw_species_shm.emplace_back(*mpi);

    // Per-species temporaries holding the heavy fields read on root.
    // These are local to read_vnl_h5 and freed at end of scope, so the
    // per-rank allocation only lives on the global root for the duration
    // of this block.
    struct heavy_tmp {
      nda::array<double,2> aewfc;
      nda::array<double,2> pswfc;
      nda::array<double,3> qfuncl;
      nda::array<double,4> deltaC;
      nda::array<double,2> ex_cvij;
      nda::array<double,2> core_aewfc;
    };
    std::vector<heavy_tmp> heavy_root(nsp);

    if(mpi->comm.root()) {
      bool has_species_grp = grp0.has_subgroup("Hamiltonian") &&
        grp0.open_group("Hamiltonian").has_subgroup("Species");
      if(!has_species_grp) {
        app_warning("/Hamiltonian/Species group missing in h5 file. "
                    "Per-species PAW data will be empty; regenerate with "
                    "the latest pw2coqui to enable it.");
      } else {
        h5::group hgrp = grp0.open_group("Hamiltonian");
        h5::group sp_grp = hgrp.open_group("Species");
        for(int nt=0; nt<nsp; ++nt) {
          std::string nt_name = "nt"+std::to_string(nt);
          if(!sp_grp.has_subgroup(nt_name)) continue;
          h5::group nt_grp = sp_grp.open_group(nt_name);
          auto& sp = paw_species[nt];
          auto& tmp = heavy_root[nt];
          std::string kind;
          h5::h5_read_attribute(nt_grp, "species_kind", kind);
          sp.is_paw  = (kind == "paw");
          sp.is_uspp = (kind == "uspp");
          h5::h5_read_attribute(nt_grp, "mesh",   sp.mesh);
          h5::h5_read_attribute(nt_grp, "nbeta",  sp.nbeta);
          h5::h5_read_attribute(nt_grp, "kkbeta", sp.kkbeta);
          h5::h5_read_attribute(nt_grp, "nh",     sp.nh);
          sp.r.resize(sp.mesh);   nda::h5_read(nt_grp, "r",   sp.r);
          sp.rab.resize(sp.mesh); nda::h5_read(nt_grp, "rab", sp.rab);
          if(sp.is_paw && nt_grp.has_subgroup("paw")) {
            h5::group pgrp = nt_grp.open_group("paw");
            h5::h5_read_attribute(pgrp, "lmax_aug", sp.lmax_aug);
            h5::h5_read_attribute(pgrp, "raug",     sp.raug);
            h5::h5_read_attribute(pgrp, "iraug",    sp.iraug);
            // pfunc, ptfunc, augmom are derivable from aewfc/pswfc/qfuncl
            // (see species_paw_t comment) — not loaded.
            try { nda::h5_read(pgrp, "ae_vloc",    sp.ae_vloc); }    catch(...) {}
            try { nda::h5_read(pgrp, "ae_rho_atc", sp.ae_rho_atc); } catch(...) {}
            // PS-side counterparts needed to reconstruct paw_init_keeq inside
            // CoQui (rather than relying on QE's ddd_paw being frozen at ρ_QE).
            try { nda::h5_read(pgrp, "vloc_ps",    sp.vloc_ps); }    catch(...) {}
            try { nda::h5_read(pgrp, "rho_atc_ps", sp.rho_atc_ps); } catch(...) {}
          }
          if(sp.is_paw || sp.is_uspp) {
            try { nda::h5_read(nt_grp, "aewfc",  tmp.aewfc); }  catch(...) {}
            try { nda::h5_read(nt_grp, "pswfc",  tmp.pswfc); }  catch(...) {}
            try { nda::h5_read(nt_grp, "qfuncl", tmp.qfuncl); } catch(...) {}
            // Angular momentum metadata for q+G evaluation of the
            // augmentation function (qvan2 reconstruction in CoQui).
            try { nda::h5_read(nt_grp, "lll",    sp.lll);    } catch(...) {}
            try { nda::h5_read(nt_grp, "nhtol",  sp.nhtol);  } catch(...) {}
            try { nda::h5_read(nt_grp, "nhtolm", sp.nhtolm); } catch(...) {}
            try { nda::h5_read(nt_grp, "indv",   sp.indv);   } catch(...) {}
          }
          // One-center Coulomb residual ΔC = K_AE − K_PS, raw ke%k from
          // PAW_init_fock_kernel exported by pw2coqui (in proper Hartree).
          if(sp.is_paw && nt_grp.has_subgroup("Onecenter")) {
            h5::group ogrp = nt_grp.open_group("Onecenter");
            try { nda::h5_read(ogrp, "deltaC", tmp.deltaC); } catch(...) {}
            // Frozen core-valence exact-exchange kernel (ABINIT ex_cvij). Optional:
            // absent for GIPAW-less / core-valence-free datasets. Warned about below.
            try { nda::h5_read(ogrp, "ex_cvij", tmp.ex_cvij); } catch(...) {}
          }
          // GIPAW core orbitals (notes §7 — required for explicit
          // core-valence/core-core exchange). Absent for non-GIPAW pseudos.
          if(sp.is_paw && nt_grp.has_subgroup("Core")) {
            h5::group cgrp = nt_grp.open_group("Core");
            h5::h5_read_attribute(cgrp, "ncore_orbitals", sp.ncore_orbitals);
            try { nda::h5_read(cgrp, "n",      sp.core_n); }     catch(...) {}
            try { nda::h5_read(cgrp, "l",      sp.core_l); }     catch(...) {}
            try { nda::h5_read(cgrp, "ae_wfc", tmp.core_aewfc); } catch(...) {}
          }
        }
      }
    }
    mpi->comm.barrier();

    // Broadcast paw_species data to non-root ranks. The h5 read above only
    // executes on comm.root; without this broadcast, downstream consumers
    // (paw_aug_thc, paw_aug_q_eval, local_isdf, hartree_xc_energy) get
    // empty species data on non-root ranks and either silently skip work
    // or hang on collective ops triggered by inconsistent metadata.
    auto bcast_array_1 = [this](nda::array<double,1>& a) {
      long sz = a.size();
      mpi->comm.broadcast_value(sz);
      if (!mpi->comm.root()) a.resize(sz);
      if (sz > 0) mpi->comm.broadcast_n(a.data(), sz, 0);
    };
    auto bcast_iarray_1 = [this](nda::array<int,1>& a) {
      long sz = a.size();
      mpi->comm.broadcast_value(sz);
      if (!mpi->comm.root()) a.resize(sz);
      if (sz > 0) mpi->comm.broadcast_n(a.data(), sz, 0);
    };

    // Helpers that broadcast a heavy field's shape, allocate a node-shared
    // SHM segment of that shape (collective on all ranks; sized to the
    // global root's data), copy on global root, internode-broadcast across
    // node-roots, and bind the species_paw_t view to the SHM's local().
    // For empty inputs (size == 0 on root) the SHM is left at its dummy
    // 1×… shape and the view is set to the empty zero-size sub-view.
    auto bcast_to_shm_2 = [this](nda::array<double,2>& tmp_root,
                                  sarray_t<nda::array_view<double,2>>& shm,
                                  nda::array_view<double,2>& view) {
      std::array<long,2> sh{0,0};
      if (mpi->comm.root()) sh = {tmp_root.shape()[0], tmp_root.shape()[1]};
      mpi->comm.broadcast_n(sh.data(), 2, 0);
      if (sh[0] == 0 || sh[1] == 0) { view = nda::array_view<double,2>{}; return; }
      shm = math::shm::make_shared_array<nda::array_view<double,2>>(*mpi, {sh[0],sh[1]});
      shm.win().fence();
      if (mpi->comm.root()) shm.local() = tmp_root;
      shm.win().fence();
      if (mpi->node_comm.root())
        mpi->internode_comm.broadcast_n(shm.local().data(), shm.size(), 0);
      mpi->comm.barrier();
      view.rebind(shm.local());
    };
    auto bcast_to_shm_3 = [this](nda::array<double,3>& tmp_root,
                                  sarray_t<nda::array_view<double,3>>& shm,
                                  nda::array_view<double,3>& view) {
      std::array<long,3> sh{0,0,0};
      if (mpi->comm.root())
        sh = {tmp_root.shape()[0], tmp_root.shape()[1], tmp_root.shape()[2]};
      mpi->comm.broadcast_n(sh.data(), 3, 0);
      if (sh[0]*sh[1]*sh[2] == 0) { view = nda::array_view<double,3>{}; return; }
      shm = math::shm::make_shared_array<nda::array_view<double,3>>(*mpi, {sh[0],sh[1],sh[2]});
      shm.win().fence();
      if (mpi->comm.root()) shm.local() = tmp_root;
      shm.win().fence();
      if (mpi->node_comm.root())
        mpi->internode_comm.broadcast_n(shm.local().data(), shm.size(), 0);
      mpi->comm.barrier();
      view.rebind(shm.local());
    };
    auto bcast_to_shm_4 = [this](nda::array<double,4>& tmp_root,
                                  sarray_t<nda::array_view<double,4>>& shm,
                                  nda::array_view<double,4>& view) {
      std::array<long,4> sh{0,0,0,0};
      if (mpi->comm.root())
        sh = {tmp_root.shape()[0], tmp_root.shape()[1],
              tmp_root.shape()[2], tmp_root.shape()[3]};
      mpi->comm.broadcast_n(sh.data(), 4, 0);
      if (sh[0]*sh[1]*sh[2]*sh[3] == 0) { view = nda::array_view<double,4>{}; return; }
      shm = math::shm::make_shared_array<nda::array_view<double,4>>(*mpi, {sh[0],sh[1],sh[2],sh[3]});
      shm.win().fence();
      if (mpi->comm.root()) shm.local() = tmp_root;
      shm.win().fence();
      if (mpi->node_comm.root())
        mpi->internode_comm.broadcast_n(shm.local().data(), shm.size(), 0);
      mpi->comm.barrier();
      view.rebind(shm.local());
    };

    for (int nt = 0; nt < nsp; ++nt) {
      auto& sp     = paw_species[nt];
      auto& sp_shm = paw_species_shm[nt];
      auto& tmp    = heavy_root[nt];
      // scalars
      mpi->comm.broadcast_value(sp.is_paw);
      mpi->comm.broadcast_value(sp.is_uspp);
      mpi->comm.broadcast_value(sp.mesh);
      mpi->comm.broadcast_value(sp.nbeta);
      mpi->comm.broadcast_value(sp.kkbeta);
      mpi->comm.broadcast_value(sp.nh);
      mpi->comm.broadcast_value(sp.lmax_aug);
      mpi->comm.broadcast_value(sp.raug);
      mpi->comm.broadcast_value(sp.iraug);
      mpi->comm.broadcast_value(sp.ncore_orbitals);
      // small per-rank arrays
      bcast_array_1(sp.r);
      bcast_array_1(sp.rab);
      bcast_iarray_1(sp.lll);
      bcast_iarray_1(sp.nhtol);
      bcast_iarray_1(sp.nhtolm);
      bcast_iarray_1(sp.indv);
      bcast_array_1(sp.ae_vloc);
      bcast_array_1(sp.ae_rho_atc);
      bcast_array_1(sp.vloc_ps);
      bcast_array_1(sp.rho_atc_ps);
      bcast_array_1(sp.core_n);
      bcast_array_1(sp.core_l);
      // heavy fields → SHM (one copy per node).
      bcast_to_shm_2(tmp.aewfc,      sp_shm.aewfc,      sp.aewfc);
      bcast_to_shm_2(tmp.pswfc,      sp_shm.pswfc,      sp.pswfc);
      bcast_to_shm_3(tmp.qfuncl,     sp_shm.qfuncl,     sp.qfuncl);
      bcast_to_shm_4(tmp.deltaC,     sp_shm.deltaC,     sp.deltaC);
      bcast_to_shm_2(tmp.ex_cvij,    sp_shm.ex_cvij,    sp.ex_cvij);
      bcast_to_shm_2(tmp.core_aewfc, sp_shm.core_aewfc, sp.core_aewfc);
    }
    mpi->comm.barrier();

    // ---- Visibility: warn LOUDLY when frozen core-valence contributions are
    // absent for a PAW species, so they are never silently dropped. The core
    // charge feeds the core-valence Hartree; ex_cvij is the core-valence exact
    // exchange (both live entirely inside the augmentation sphere; see notes).
    for (int nt = 0; nt < nsp; ++nt) {
      auto& sp = paw_species[nt];
      if (!sp.is_paw) continue;
      bool no_core_charge = (sp.ae_rho_atc.size() == 0) &&
                            (sp.ncore_orbitals == 0 || sp.core_aewfc.size() == 0);
      // Auto-detect the core-valence exchange treatment from the h5 datasets:
      //   ex_cvij present            -> frozen Fock c-v exchange (fock)
      //   else <DFT c-v XC dataset>  -> dft_xc   [TODO: dataset TBD]
      //   else                       -> none (omitted; warned loudly below)
      // TODO: when a DFT core-valence XC dataset is defined in the h5, read a
      // per-species flag in the loading loop above, broadcast it alongside the
      // other scalars, and set sp.cv_exchange = cv_exchange_e::dft_xc here.
      sp.cv_exchange = (sp.ex_cvij.size() > 0) ? cv_exchange_e::fock
                                               : cv_exchange_e::none;
      bool no_cv_exchange = (sp.cv_exchange == cv_exchange_e::none);
      if (no_core_charge) {
        app_warning("**************************************************************************");
        app_warning("**************************************************************************");
        app_warning("***  WARNING: PAW species nt={} has NO all-electron core charge.", nt);
        app_warning("***  The CORE-VALENCE HARTREE contribution will be OMITTED (set to 0).");
        app_warning("***  Provide ae_rho_atc (AE core density) or GIPAW core orbitals in the");
        app_warning("***  mean-field h5 to include it. Total energies / QP levels are affected.");
        app_warning("**************************************************************************");
        app_warning("**************************************************************************");
      }
      if (no_cv_exchange) {
        app_warning("**************************************************************************");
        app_warning("**************************************************************************");
        app_warning("***  WARNING: PAW species nt={} has NO core-valence exchange kernel", nt);
        app_warning("***  (Onecenter/ex_cvij). The CORE-VALENCE EXACT EXCHANGE is OMITTED.");
        app_warning("***  ex_cvij (ABINIT <exact_exchange_X_matrix>) to include it.");
        app_warning("**************************************************************************");
        app_warning("**************************************************************************");
      }
    }
  }

  // Static (frozen) per-atom D for USPP/PAW (plan I2, assembled eagerly):
  //
  //   D_static(a, I, J) = dion(type(a), I, J) + alpha_x * ex_cvij(type(a), I, J)
  //
  // dion (h5 `dion`, loaded into Dnn above) is the FULL frozen D^0 per QE
  // convention (AE−PS kinetic + frozen-core-screened ionic Hartree). ex_cvij
  // is the frozen core-valence exact exchange (ABINIT <exact_exchange_X_matrix>):
  // a static one-center projector Dij contracted LINEARLY with becsum (factor
  // 1), disjoint from the density-dependent valence Fock (v_x/deltaC), so
  // holding it in the frozen per-atom D makes e_1e = Tr[Dm·H0] capture it with
  // the correct factor 1. ex_cvij is in Hartree (matches Dnn after 0.5 Ry→Ha).
  // alpha_x = exchange fraction (1 for HF/GW). Assembled here (not in the
  // dion read above) because ex_cvij is only loaded with the heavy paw_species
  // fields just above. This tensor is never mutated after this point;
  // density-dependent (Hartree-only) terms are rebuilt per evaluation via
  // compute_paw_deeq (plan I3).
  //
  // Guard on pp type: paw_species is only populated for USPP/PAW (see above),
  // so this block must NOT dereference paw_species[nt] on the NC path (empty
  // vector -> out-of-bounds). ex_cvij is PAW-only; USPP simply has size()==0.
  //
  // The core-valence exchange treatment is AUTO-DETECTED per species from the h5
  // (species_paw_t::cv_exchange, set in the loop above): 'fock' inserts the
  // frozen ex_cvij one-center Dij here; 'none' skips it (omitted, warned above);
  // 'dft_xc' (DFT-based c-v XC, dataset TBD) is NOT YET IMPLEMENTED and aborts.
  if(ptype == pp_uspp_t or ptype == pp_paw_t) {
    Dnn_atom_static = sarray_t<nda::array_view<ComplexType,3>>(*mpi,
                        {std::max(1,nat), nhm*npol, nhm*npol});
    mpi->node_comm.barrier();
    if(mpi->node_comm.root()) {
      const double alpha_x = 1.0;
      auto Dloc_sp = Dnn.local();
      auto Dloc_st = Dnn_atom_static.local();
      Dloc_st() = ComplexType(0.0);
      for(int ia=0; ia<nat; ++ia) {
        int nt = ityp(ia);
        // dion replica (already in Ha after the 0.5 Ry→Ha scale above).
        for(int n=0; n<nhm*npol; ++n)
          for(int m=0; m<nhm*npol; ++m)
            Dloc_st(ia, n, m) = Dloc_sp(nt, n, m);
        auto const& sp = paw_species[nt];
        if(!sp.is_paw) continue;
        if(sp.cv_exchange == cv_exchange_e::none) continue;  // omitted (warned above)
        utils::check(sp.cv_exchange == cv_exchange_e::fock,
          "pseudopot: core-valence exchange 'dft_xc' (DFT-based core-valence XC) is "
          "NOT YET IMPLEMENTED for PAW species nt={}: a DFT c-v XC dataset was "
          "detected in the h5 but cannot be used yet. TODO: implement + unit test.", nt);
        // fock: insert the frozen ex_cvij one-center Dij (ex_cvij guaranteed present).
        int nh_a = sp.nh;
        for(int p=0; p<npol; ++p)
          for(int n=0; n<nh_a; ++n)
            for(int m=0; m<nh_a; ++m)
              Dloc_st(ia, n*npol+p, m*npol+p) +=
                  ComplexType(alpha_x * sp.ex_cvij(n,m), 0.0);
      }
    }
    mpi->node_comm.barrier();
    if(mpi->node_comm.root())
      mpi->internode_comm.broadcast_n(Dnn_atom_static.local().data(),
                                      Dnn_atom_static.size(), 0);
    mpi->comm.barrier();
  }
  mpi->node_comm.barrier();

  // calculate projectors
  sarray_t<nda::array_view<long,2>> sk2g(*mpi,{nk,npwx});
  auto k2g = sk2g.local();
  auto wfc_g = mf.wfc_truncated_grid();  
  long ngm = wfc_g->size();
  auto fft2gv = wfc_g->fft_to_gv();
  long wfc_nnr = wfc_g->nnr(); 

  // setup index mappings
  {
    long NX = wfc_g->mesh(0), NY = wfc_g->mesh(1), NZ = wfc_g->mesh(2);
    for( int ik=0; ik<nk; ik++ ) {
      if(  ik%np != rank ) continue;
      nda::array<int,2> mill(npw(ik),3);
      nda::h5_read(grp,"miller_k"+std::to_string(ik),mill);
      // map miller index to wfc_g truncated grid
      for( int i=0; i<npw(ik); i++ ) {
        long n1 = mill(i,0); if(n1<0) n1 += NX;
        long n2 = mill(i,1); if(n2<0) n2 += NY;
        long n3 = mill(i,2); if(n3<0) n3 += NZ;
        utils::check(n1 < NX, "read_vnl_h5: Index out of range. i:{}, n:{}, NX:{}",i,n1,NX);
        utils::check(n2 < NY, "read_vnl_h5: Index out of range. i:{}, n:{}, NY:{}",i,n2,NY);
        utils::check(n3 < NZ, "read_vnl_h5: Index out of range. i:{}, n:{}, NZ:{}",i,n3,NZ);
        long N = (n1*NY + n2)*NZ + n3;
        utils::check( N >= 0 and N < wfc_nnr, "read_vnl_h5: Index out of range. N:{}, nnr:{}",N,wfc_nnr);
        k2g(ik,i) = fft2gv(N); 
        utils::check( k2g(ik,i) >= 0 and k2g(ik,i) < ngm, "read_vnl_h5: Index not mapped in truncated grid. "); 
      } 
    }
    mpi->comm.barrier();
    if(mpi->node_comm.root()) 
      mpi->internode_comm.all_reduce_in_place_n(k2g.data(),k2g.size(),std::plus<>{});
    mpi->comm.barrier();
  }

  Pskna = sarray_t<nda::array_view<ComplexType,4>>(*mpi,{nspin,nk,long(nkb)*npol,nbnd});
  auto Ploc = Pskna.local();

  if( nkb == 0 ) return;

  using local_4Array_t = typename nda::array<ComplexType,4>;
  // default is no distribution over basis, e.g. pw index
  auto dPsia = mf::read_distributed_orbital_set_ibz<local_4Array_t>(mf,mpi->comm,'w');
  auto psi = dPsia.local();
  utils::check(psi.extent(3) == npol*ngm, "Shape mismatch.");

  // MAM: This is still not optimal! Could be problematic in large grid problems!
  // {nk,nkb,ngm}
  nda::array<ComplexType,2> buff(1,npwx);
  nda::array<ComplexType,1> vkb(ngm);
  // read and reorder vkb
  for( auto [is,s] : itertools::enumerate(dPsia.local_range(0)) ) {
    for( auto [ik,k] : itertools::enumerate(dPsia.local_range(1)) ) {
      for( int ib=0; ib<nkb; ++ib ) { 
        auto b_k = buff(all,range(npw(k)));
        auto tpl = std::tuple{range(ib,ib+1),range(npw(k))};
        nda::h5_read(grp,"projector_k"+std::to_string(k),b_k,tpl);
        vkb() = ComplexType(0.0);
        for( auto [in,n] : itertools::enumerate(k2g(k,range(npw(k)))) ) 
          vkb(n) = std::conj(buff(0,in)); 
        for(int ip=0; ip<npol; ++ip) 
          nda::blas::gemv(ComplexType(1.0),psi(is,ik,all,range(ip*ngm,(ip+1)*ngm)),vkb,
                          ComplexType(0.0),Ploc(s,k,ib*npol+ip,dPsia.local_range(2)));
      }
    }
  } 
  mpi->comm.barrier();
  if(mpi->node_comm.root()) 
    mpi->internode_comm.all_reduce_in_place_n(Ploc.data(),Ploc.size(),std::plus<>{});
  mpi->comm.barrier();

}

// This should only be called by a single task
void pseudopot::save(std::string fname, bool append)
{ 
  if(ptype == pp_FILE_t) return; 
  char mode = (append?'a':'w');
  h5::file file;
  try {
    file = h5::file(fname, mode);
  } catch(...) {
    APP_ABORT("Failed to open h5 file: {}, mode:{}",fname,mode);
  }
  h5::group grp(file);
  pseudopot_to_h5(fft_mesh_aug,grp,input_file_name,input_file_type);
}

// This should only be called by a single task
// MAM: save from files directly, to avoid needing to construct the object
void pseudopot::save(h5::group& grp0)
{
  if(ptype == pp_FILE_t) return; 
  pseudopot_to_h5(fft_mesh_aug,grp0,input_file_name,input_file_type);
}

void pseudopot::add_vnl_impl(nda::range k_range, nda::range b_range, 
                   nda::ArrayOfRank<3> auto const& Dion,
		   math::nda::DistributedArrayOfRank<4> auto & Hij)
{
  using nda::range;
  // checks have already been done 
  decltype(range::all) all;
  constexpr auto MEM = memory::get_memory_space<std::decay_t<decltype(Hij.local())>>(); 

  auto k_range_loc = Hij.local_range(1) + k_range.first();
  auto b_range_loc = Hij.local_range(2) + b_range.first();
  long nkb = Pskna.shape()[2]/npol;
  long nbnd = b_range_loc.size(); 

  if( nkb == 0 ) return;

  // non-local part, directly into Hij
  auto Hijloc = Hij.local();
  auto Ploc = Pskna.local();

  // Hij(s,k,a,b) = sum_np_qn' conj(Pskna(s,k,np,a)) D(np,n'q) Pskna(s,k,n'q,b) 
  // for each (s,k)
  // T(a,n'q) = sum_np conj(Pskna(s,k,np,a)) D(np,n'q)
  // Hij(s,k,a,b) = sum_n'q T(a,n'q) * Pskna(s,k,n'q,b) 
  if constexpr (MEM == HOST_MEMORY) {     
    memory::array<MEM, ComplexType, 2> T(nbnd,nkb*npol);  
    for( auto [is,s] : itertools::enumerate(Hij.local_range(0)) )
      for( auto [ik,k] : itertools::enumerate(k_range_loc) ) {
        for( auto [ia,nt] : itertools::enumerate(ityp) )
  	{
          if(nh(nt) == 0) continue;
          long id = ( ptype == pp_ncpp_t ? nt : ia ); 
          nda::blas::gemm(ComplexType(1.0),
                  nda::dagger(Ploc(s,k,range(ofs(ia)*npol,(ofs(ia)+nh(nt))*npol),b_range_loc)),
                  Dion(id,range(nh(nt)*npol),range(nh(nt)*npol)),
                  ComplexType(0.0),T(all,range(ofs(ia)*npol,(ofs(ia)+nh(nt))*npol)));
        }
        nda::blas::gemm(ComplexType(1.0),T,Ploc(s,k,all,b_range),
                        ComplexType(1.0),Hijloc(is,ik,all,all)); 
      }
  } else { 
#if defined(ENABLE_DEVICE)
    long nk = k_range_loc.size(); 
    memory::array<MEM, ComplexType, 4> T(Hij.local_range(0).size(),nk,nbnd,nkb*npol);  
// MAM: cutensor always synchronizes right now, fix this!!!
//      or submit with streams!
// MAM: Keeping Pskna in CPU memory and making transfers every time.
// This tensor gets large, no need to keep it in GPU memory outside of this routine.
// Measure transfer time and print! This could be slow!
    auto Ploc_d = nda::to_device(Ploc);
    auto Dion_d = nda::to_device(Dion);
    for( auto [is,s] : itertools::enumerate(Hij.local_range(0)) )
      for( auto [ia,nt] : itertools::enumerate(ityp) )
      {
        if(nh(nt) == 0) continue;
        long id = ( ptype == pp_ncpp_t ? nt : ia ); 
        nda::tensor::contract(
          nda::conj(Ploc_d(s,k_range_loc,range(ofs(ia)*npol,(ofs(ia)+nh(nt))*npol),b_range_loc)),"kma",
          Dion_d(id,range(nh(nt)*npol),range(nh(nt)*npol)),"mn",
          T(is,all,all,range(ofs(ia)*npol,(ofs(ia)+nh(nt))*npol)),"kan");
      }
    nda::tensor::contract(ComplexType(1.0),T,"skan",
                          Ploc_d(Hij.local_range(0),k_range_loc,all,b_range),"sknb",
                          ComplexType(1.0),Hijloc,"skab");
#else
    static_assert(MEM!=HOST_MEMORY, "Error: Device code without device support.");
#endif
  }
}

// MAM: This routine should take an mpi_context and use it, instead of mpi
//      since we are currently calling it with a different set of processes
template< nda::ArrayOfRank<3> Arr3, nda::ArrayOfRank<4> Arr4>
void pseudopot::add_vpp_impl(boost::mpi3::communicator& comm,
                   nda::range k_range, nda::range b_range, 
		   math::nda::DistributedArrayOfRank<4> auto const& psi,
		   math::nda::DistributedArrayOfRank<4> auto & hpsi,
		   math::nda::DistributedArrayOfRank<4> auto & Hij,
                   const Arr3 * nii, const Arr4 * nij)
{
  pots::potential_t vG(ptree{});

  decltype(nda::range::all) all;
  constexpr auto MEM = memory::get_memory_space<std::decay_t<decltype(psi.local())>>(); 
  constexpr auto MEM1 = memory::get_memory_space<std::decay_t<decltype(hpsi.local())>>(); 
  constexpr auto MEM2 = memory::get_memory_space<std::decay_t<decltype(Hij.local())>>(); 
  static_assert(MEM == MEM1, "Memory mismatch.");
  static_assert(MEM == MEM2, "Memory mismatch.");

  auto k_range_loc = psi.local_range(1) + k_range.first();
  utils::check(k_range.size() == psi.global_shape()[1], "Shape mismatch: {},{}",k_range.size(),psi.global_shape()[1]);
  utils::check(b_range.size() == psi.global_shape()[2], "Shape mismatch: {},{}",b_range.size(),psi.global_shape()[2]);
  utils::check(psi.global_shape() == hpsi.global_shape(), "Shape mismatch");
  utils::check(psi.local_shape() == hpsi.local_shape(), "Shape mismatch");
  utils::check(psi.origin() == hpsi.origin(), "Shape mismatch");
  utils::check(psi.local_range(3) == nda::range{0,npol*swfc_to_rho.size()}, 
               "Range mismatch");
  utils::check(psi.grid()[3] == 1, "Processor grid mismatch");
  utils::check(k_range_loc.first() >= 0 and
               k_range_loc.last()  <= nkpts_ibz, "Range mismatch.");
  utils::check(psi.global_shape()[0] == Hij.global_shape()[0], "Shape mismatch");
  utils::check(psi.global_shape()[1] == Hij.global_shape()[1], "Shape mismatch");
  utils::check(psi.global_shape()[2] == Hij.global_shape()[2], "Shape mismatch");
  utils::check(psi.global_shape()[2] == Hij.global_shape()[3], "Shape mismatch");
  utils::check(psi.local_shape()[0] == Hij.local_shape()[0], "Shape mismatch");
  utils::check(psi.local_shape()[1] == Hij.local_shape()[1], "Shape mismatch");
  utils::check(psi.local_shape()[2] == Hij.local_shape()[2], "Shape mismatch");
  utils::check(Hij.global_shape()[3] == Hij.local_shape()[3], "Shape mismatch");

  /*
   *   1. calculate charge density and fft to G space
   *   2. symmetrize density
   *   3. multiply by coulomb
   *   4. fft to real space
   *   5. add to vloc
   */
  if( nii != nullptr or nij != nullptr ) {

    auto mpi_local_context = utils::make_mpi_context(comm);

    // local pseudopotential + hartree
    sarray_t<nda::array_view<ComplexType,1>> svr(mpi_local_context,{nnr_aug});
    auto vr = svr.local();
    auto vltot = svloc.local();

    utils::check( nii == nullptr or nij == nullptr, 
                  "Error in pseudo::add_vpp_impl: Both nii and nij!!");
    utils::check( k_range.first() == 0 and  k_range.last() == nkpts_ibz, 
                 "Error in add_vloc: add_hartree requires full kpoint range.");
    // Calculates hartree potential on the soft+augmentation charge density. 
    if( nii != nullptr)
      hamilt::v_h(*mpi, vG, *this, npol, fft_mesh_aug, lattv, recv,
                  swfc_to_rho.local(), kpts, kp_to_ibz,
                  kp_trev, kp_symm, symm_list, *nii, psi, false, svr);
    else
      hamilt::v_h(*mpi, vG, *this, npol, fft_mesh_aug, lattv, recv,
                  swfc_to_rho.local(), kpts, kp_to_ibz,
                  kp_trev, kp_symm, symm_list, *nij, psi, false, svr);

    mpi->node_comm.barrier();
    // accumulate on vltot, remove afterwards
    if(mpi->node_comm.root()) {
      // vr is spin independent and acts only on diagonal components in polarization space
      for( auto is: nda::range(vltot.extent(0)) ) {
        for( auto ip: nda::range(vltot.extent(1)) ) {
          vltot(is,ip*npol+ip,all) += vr;
        }
      }
    }
    mpi->node_comm.barrier();

    // local potential
    hamilt::add_vloc(npol,fft_mesh_aug,swfc_to_rho.local(),vltot,psi,hpsi);

    mpi->node_comm.barrier();
    // restore vltot (remove vr)
    if(mpi->node_comm.root()) {
      for( auto is: nda::range(vltot.extent(0)) ) {
        for( auto ip: nda::range(vltot.extent(1)) ) {
          vltot(is,ip*npol+ip,all) -= vr;
        }
      }
    }
    mpi->node_comm.barrier();

    // Native PAW deeq: build the per-channel D from V_eff = V_loc + V_H
    // (vltot + vr) on the smooth grid, plus the static (dion + ex_cvij)
    // baseline and the radial AE−PS one-center Hartree. PerType scaling means
    // no occupation/N_k is folded into the channel. Built only on PAW/USPP;
    // NCPP falls through to the bare branch.
    // TODO (plan A2/A3): wire the nij overload through compute_paw_deeq(nij)
    // as well (needs the symmetry-correct full-BZ nij becsum); today nij
    // falls through to the static-only branch below.
    if (ptype != pp_ncpp_t && nii != nullptr) {
      sarray_t<nda::array_view<ComplexType,1>> svfull(mpi_local_context,{nnr_aug});
      auto vfull = svfull.local();
      if (mpi->node_comm.root()) {
        // svloc holds V_loc (Ha); vr holds V_H (Ha) for the converged density.
        // Build V_eff = V_loc + V_H; deeq sees the L=0 spherical part of svloc
        // automatically, so we collapse the (spin, npol²) axes to scalar.
        for (long r = 0; r < nnr_aug; ++r)
          vfull(r) = svloc.local()(0, 0, r) + vr(r);
      }
      mpi->node_comm.barrier();
      auto Dion_native = compute_paw_deeq(*nii, vfull,
                                          /*include_static=*/true);
      add_vnl_impl(k_range, b_range, Dion_native, Hij);
      return;
    }

  } else {

    // local potential
    auto vltot = svloc.local();
    hamilt::add_vloc(npol,fft_mesh_aug,swfc_to_rho.local(),vltot,psi,hpsi);

  }

  // Non-local part, directly into Hij. add_vnl_impl indexes Dion(id, ...)
  // with id = (ncpp ? nt : ia). NCPP → species-resolved Dnn.
  // PAW/USPP + nii is handled above via the native `compute_paw_deeq` early
  // return. PAW/USPP no-density → static-only H0 per plan I5 (Hartree and
  // exchange are supplied by the ERI objects in the SCF classes).
  // PAW/USPP + nij currently ALSO falls through to static-only — the native
  // `compute_paw_deeq(nij)` wiring (identical operator to the nii overload)
  // lands with plan A2/A3 (needs the symmetry-correct nij becsum).
  if (ptype == pp_ncpp_t)
    add_vnl_impl(k_range, b_range, Dnn.local(),             Hij);
  else
    add_vnl_impl(k_range, b_range, Dnn_atom_static.local(), Hij);
}

// Standalone helper: add the USPP/PAW augmentation to a smooth-grid pair
// density evaluated at a single (atom-list × G-grid) configuration.
//
// Inputs:
//   becsum_aIJ : per-atom, per-(I,J) coefficient ⟨ψ_a|β_aI⟩ q_IJ ⟨β_aJ|ψ_b⟩
//                (caller computes from Pskna; shape (nat, nij_max))
//   gvec_phase : structure factor e^{-iG·τ_a}, shape (nat, ngm_dense)
// Output:
//   rhoG       : input density on dense G grid, shape (ngm_dense,);
//                augmented in place: rhoG += Σ_a Σ_IJ becsum_aIJ Q^IJ_nt(a)(G) e^{-iG·τ_a}
//
// Independent of the Hartree/exchange wiring above.
void pseudopot::add_augmentation_to_pairdensity(
    nda::ArrayOfRank<2> auto const& becsum_aIJ,
    nda::ArrayOfRank<2> auto const& gvec_phase,
    nda::ArrayOfRank<1> auto       & rhoG) const
{
  if (ptype == pp_ncpp_t) return;
  utils::check(qgm.local().size() > 0,
               "add_augmentation_to_pairdensity: qgm not populated.");
  utils::check(ngm_dense > 0,
               "add_augmentation_to_pairdensity: ngm_dense unknown.");
  long ngm = rhoG.extent(0);
  utils::check(ngm == ngm_dense,
               "add_augmentation_to_pairdensity: rhoG/ngm_dense mismatch ({} vs {})",
               ngm, ngm_dense);
  utils::check(gvec_phase.extent(1) == ngm,
               "add_augmentation_to_pairdensity: gvec_phase G-dim mismatch");

  long nat = ityp.extent(0);
  utils::check(becsum_aIJ.extent(0) == nat, "becsum atom-dim mismatch");
  utils::check(gvec_phase.extent(0) == nat, "gvec_phase atom-dim mismatch");

  auto qg = qgm.local();
  for (long ia=0; ia<nat; ++ia) {
    int nt = ityp(ia);
    long nij = static_cast<long>(nh(nt))*(nh(nt)+1)/2;
    if (nij == 0) continue;
    for (long ij=0; ij<nij; ++ij) {
      ComplexType b = becsum_aIJ(ia, ij);
      if (b == ComplexType(0.0)) continue;
      for (long g=0; g<ngm; ++g) {
        rhoG(g) += b * qg(nt, ij, g) * gvec_phase(ia, g);
      }
    }
  }
}

void pseudopot::add_Vpp(boost::mpi3::communicator& comm,
                   nda::range k_range, nda::range b_range, 
		   math::nda::DistributedArrayOfRank<4> auto const& psi,
		   math::nda::DistributedArrayOfRank<4> auto & hpsi,
		   math::nda::DistributedArrayOfRank<4> auto & Hij)
{
  constexpr auto MEM = memory::get_memory_space<std::decay_t<decltype(psi.local())>>(); 
  constexpr auto MEM1 = memory::get_memory_space<std::decay_t<decltype(hpsi.local())>>();
  constexpr auto MEM2 = memory::get_memory_space<std::decay_t<decltype(Hij.local())>>();
  static_assert(MEM == MEM1, "Memory mismatch.");
  static_assert(MEM == MEM2, "Memory mismatch.");
  memory::array<MEM,ComplexType,3>* p3 = nullptr;
  memory::array<MEM,ComplexType,4>* p4 = nullptr;
  add_vpp_impl(comm,k_range,b_range,psi,hpsi,Hij,p3,p4);
}

void pseudopot::add_Vpp(boost::mpi3::communicator& comm,
                   nda::range k_range, nda::range b_range, 
                   nda::ArrayOfRank<3> auto const& nii, 
                   math::nda::DistributedArrayOfRank<4> auto const& psi,
                   math::nda::DistributedArrayOfRank<4> auto & hpsi,
                   math::nda::DistributedArrayOfRank<4> auto & Hij)
{
  constexpr auto MEM = memory::get_memory_space<std::decay_t<decltype(psi.local())>>(); 
  constexpr auto MEM1 = memory::get_memory_space<std::decay_t<decltype(hpsi.local())>>();
  constexpr auto MEM2 = memory::get_memory_space<std::decay_t<decltype(Hij.local())>>();
  static_assert(MEM == MEM1, "Memory mismatch.");
  static_assert(MEM == MEM2, "Memory mismatch.");
  memory::array<MEM,ComplexType,4>* p4 = nullptr;
  add_vpp_impl(comm,k_range,b_range,psi,hpsi,Hij,std::addressof(nii),p4);
}

void pseudopot::add_Vpp(boost::mpi3::communicator& comm,
                   nda::range k_range, nda::range b_range, 
                   nda::ArrayOfRank<4> auto const& nij,
                   math::nda::DistributedArrayOfRank<4> auto const& psi,
                   math::nda::DistributedArrayOfRank<4> auto & hpsi,
                   math::nda::DistributedArrayOfRank<4> auto & Hij)
{ 
  constexpr auto MEM = memory::get_memory_space<std::decay_t<decltype(psi.local())>>(); 
  constexpr auto MEM1 = memory::get_memory_space<std::decay_t<decltype(hpsi.local())>>();
  constexpr auto MEM2 = memory::get_memory_space<std::decay_t<decltype(Hij.local())>>();
  static_assert(MEM == MEM1, "Memory mismatch.");
  static_assert(MEM == MEM2, "Memory mismatch.");
  memory::array<MEM,ComplexType,3>* p3 = nullptr;
  add_vpp_impl(comm,k_range,b_range,psi,hpsi,Hij,p3,std::addressof(nij));
}

// MAM: This routine should take an mpi_context and use it, instead of mpi
template<nda::ArrayOfRank<3> Arr3, nda::ArrayOfRank<4> Arr4>
void pseudopot::add_Hartree_impl(nda::range k_range, nda::range b_range,
                                 math::nda::DistributedArrayOfRank<4> auto const& psi,
                                 math::nda::DistributedArrayOfRank<4> auto & hpsi,
                                 math::nda::DistributedArrayOfRank<4> auto & Vij,
                                 const Arr3 *nii, const Arr4 *nij, bool symmetrize) {
  constexpr auto MEM = memory::get_memory_space<std::decay_t<decltype(psi.local())>>();
  constexpr auto MEM1 = memory::get_memory_space<std::decay_t<decltype(hpsi.local())>>();
  static_assert(MEM == MEM1, "Memory mismatch.");

  auto k_range_loc = psi.local_range(1) + k_range.first();
  utils::check(k_range.size() == psi.global_shape()[1], "Shape mismatch: {},{}",k_range.size(),psi.global_shape()[1]);
  utils::check(psi.global_shape() == hpsi.global_shape(), "Shape mismatch");
  utils::check(psi.local_shape() == hpsi.local_shape(), "Shape mismatch");
  utils::check(psi.origin() == hpsi.origin(), "Shape mismatch");
  utils::check(psi.local_range(3) == nda::range{0,npol*swfc_to_rho.size()},
               "Range mismatch");
  utils::check(psi.grid()[3] == 1, "Processor grid mismatch");
  utils::check(k_range_loc.first() >= 0 and
               k_range_loc.last()  <= nkpts_ibz, "Range mismatch.");

  auto sv_hartree = make_shared_array<nda::array_view<ComplexType, 1>>(*mpi, {nnr_aug});
  auto v_hartree = sv_hartree.local();

  // MAM: this must be passed to the routine
  pots::potential_t vG(ptree{});

  utils::check(nii == nullptr or nij == nullptr,
               "Error in pseudo::add_Hartree_impl: Both nii and nij exist!");
  utils::check(k_range.first() == 0 and k_range.last() == nkpts_ibz,
               "Error in add_Hartree_impl: add_hartree requires full kpoint range.");
  // calculate and add hartree term. The pseudopot-taking hamilt::v_h
  // delegates to the smooth-only v_h then (for USPP/PAW) adds the
  // compensation-charge augmentation in G-space; NCPP no-ops the augment.
  if (nii != nullptr)
    hamilt::v_h(*mpi, vG, *this, npol, fft_mesh_aug, lattv, recv,
                swfc_to_rho.local(), kpts, kp_to_ibz,
                kp_trev, kp_symm, symm_list, *nii, psi, symmetrize, sv_hartree);
  else
    hamilt::v_h(*mpi, vG, *this, npol, fft_mesh_aug, lattv, recv,
                swfc_to_rho.local(), kpts, kp_to_ibz,
                kp_trev, kp_symm, symm_list, *nij, psi, symmetrize, sv_hartree);

  // add v_hartree to hpsi
  hamilt::add_vloc(npol, fft_mesh_aug, swfc_to_rho.local(), v_hartree, psi, hpsi);

  // PAW/USPP: build the native one-center deeq (radial AE−PS + dynamic
  // G-space ∫V_H·Q from the smooth V_H(r) just computed; NO static, since
  // Vij is the pure Hartree matrix) and contract it into Vij via add_vnl_impl
  // — the single matrix-touching path, mirroring how add_vpp_impl forms Hij.
  // No QE deeq, no XC. NCPP / non-augmented species → zero Dion (no-op).
  // The deeq is a functional of the supplied density (diagonal nii or full
  // nij), NOT of the QE mean-field — see notes/paw_deeq_scaling_derivation.md.
  if (ptype != pp_ncpp_t) {
    if (nii != nullptr) {
      auto Dion_H = compute_paw_deeq(*nii, v_hartree, /*include_static=*/false);
      add_vnl_impl(k_range, b_range, Dion_H, Vij);
    } else if (nij != nullptr) {
      // Full density-matrix path: becsum via compute_becsum_full (now folds the
      // 1/N_k k-weight), so the one-center radial Hartree matches the smooth
      // compensation charge that hamilt::v_h(*nij,...) already added above.
      auto Dion_H = compute_paw_deeq(*nij, v_hartree, /*include_static=*/false);
      add_vnl_impl(k_range, b_range, Dion_H, Vij);
    }
  }

}

void pseudopot::add_Hartree(nda::range k_range,
                            nda::ArrayOfRank<3> auto const& nii,
                            math::nda::DistributedArrayOfRank<4> auto const& psi,
                            math::nda::DistributedArrayOfRank<4> auto & hpsi,
                            math::nda::DistributedArrayOfRank<4> auto & Vij,
                            bool symmetrize) {
  nda::array<ComplexType, 4>* p4 = nullptr;
  nda::range b_range(0, psi.global_shape()[2]);
  add_Hartree_impl(k_range, b_range, psi, hpsi, Vij, std::addressof(nii), p4, symmetrize);
}

void pseudopot::add_Hartree(nda::range k_range,
                            nda::ArrayOfRank<4> auto const& nij,
                            math::nda::DistributedArrayOfRank<4> auto const& psi,
                            math::nda::DistributedArrayOfRank<4> auto & hpsi,
                            math::nda::DistributedArrayOfRank<4> auto & Vij,
                            bool symmetrize) {
  nda::array<ComplexType,3>* p3 = nullptr;
  nda::range b_range(0, psi.global_shape()[2]);
  add_Hartree_impl(k_range, b_range, psi, hpsi, Vij, p3, std::addressof(nij), symmetrize);
}

// ---------------------------------------------------------------------------
// Exact-exchange matrix elements K_{ij}(s, k_p) on the IBZ.
//
// Builds K via FFT pair densities; for USPP/PAW also adds the per-pair
// Q^IJ_a(G+Δk) augmentation. Dispatches on pp_type via the v_x_paw header,
// which delegates to the smooth-only `hamilt::v_x(...)` for NCPP.
//
// Unlike add_Hartree, which produces an hpsi correction, exchange has no
// representation as a local potential acting on a single orbital — the
// augmentation cross terms involve band-pair-dependent projector overlaps.
// add_exchange therefore writes the full K matrix directly into Kij.
// ---------------------------------------------------------------------------
void pseudopot::add_exchange(nda::range k_range,
                             nda::ArrayOfRank<3> auto const& nii,
                             math::nda::DistributedArrayOfRank<4> auto const& psi,
                             math::nda::DistributedArrayOfRank<4> auto & Kij)
{
  constexpr auto MEM  = memory::get_memory_space<std::decay_t<decltype(psi.local())>>();
  constexpr auto MEM2 = memory::get_memory_space<std::decay_t<decltype(Kij.local())>>();
  static_assert(MEM == MEM2, "pseudopot::add_exchange: psi/Kij memory mismatch");

  utils::check(k_range.first() == 0 && k_range.last() == nkpts_ibz,
               "pseudopot::add_exchange: k_range must span the full IBZ");
  utils::check(psi.global_shape()[1] == nkpts_ibz,
               "pseudopot::add_exchange: psi must be on the IBZ");
  utils::check(psi.global_shape()[3] == npol * (long)swfc_to_rho.size(),
               "pseudopot::add_exchange: psi g-dim mismatch");

  // Coulomb kernel (default: bare 4π/|G+Δk|² with G+Δk=0 zeroed).
  pots::potential_t vG(ptree{});

  hamilt::paw::v_x(*mpi, vG, *this, npol, fft_mesh_aug, lattv, recv,
                   swfc_to_rho.local(), kpts, kp_to_ibz,
                   kp_trev, kp_symm, symm_list, nii, psi, Kij,
                   paw_exx_shape_restored);
}

// Full density-matrix overload (routes to the natural-orbital v_x(nij)).
void pseudopot::add_exchange(nda::range k_range,
                             nda::ArrayOfRank<4> auto const& nij,
                             math::nda::DistributedArrayOfRank<4> auto const& psi,
                             math::nda::DistributedArrayOfRank<4> auto & Kij)
{
  constexpr auto MEM  = memory::get_memory_space<std::decay_t<decltype(psi.local())>>();
  constexpr auto MEM2 = memory::get_memory_space<std::decay_t<decltype(Kij.local())>>();
  static_assert(MEM == MEM2, "pseudopot::add_exchange: psi/Kij memory mismatch");

  utils::check(k_range.first() == 0 && k_range.last() == nkpts_ibz,
               "pseudopot::add_exchange: k_range must span the full IBZ");
  utils::check(psi.global_shape()[1] == nkpts_ibz,
               "pseudopot::add_exchange: psi must be on the IBZ");
  utils::check(psi.global_shape()[3] == npol * (long)swfc_to_rho.size(),
               "pseudopot::add_exchange: psi g-dim mismatch");

  pots::potential_t vG(ptree{});
  hamilt::paw::v_x(*mpi, vG, *this, npol, fft_mesh_aug, lattv, recv,
                   swfc_to_rho.local(), kpts, kp_to_ibz,
                   kp_trev, kp_symm, symm_list, nij, psi, Kij,
                   paw_exx_shape_restored);
}


using memory::darray_t;
using memory::host_array;
using memory::host_array_view;

template pseudopot::pseudopot(mf::MF&,std::string const);
template void pseudopot::read_vnl_pw2bgw(mf::MF &, std::string);
template void pseudopot::read_vnl_h5(mf::MF &, h5::group&); 

#define __add_Vpp__(V) \
template void pseudopot::add_Vpp(boost::mpi3::communicator&,nda::range,nda::range, \
        darray_t<V<ComplexType,4>,communicator> const&, \
        darray_t<V<ComplexType,4>,communicator>&, \
        darray_t<V<ComplexType,4>,communicator>&); \
template void pseudopot::add_Vpp(boost::mpi3::communicator&,nda::range,nda::range, \
        V<ComplexType,3> const&, \
        darray_t<V<ComplexType,4>,communicator> const&, \
        darray_t<V<ComplexType,4>,communicator>&, \
        darray_t<V<ComplexType,4>,communicator>&); \
template void pseudopot::add_Vpp(boost::mpi3::communicator&,nda::range,nda::range, \
        V<ComplexType,4> const&,  \
        darray_t<V<ComplexType,4>,communicator> const&,  \
        darray_t<V<ComplexType,4>,communicator>&,  \
        darray_t<V<ComplexType,4>,communicator>&);  \

#define __add_Vpp2__(V1,V2) \
template void pseudopot::add_Vpp(boost::mpi3::communicator&,nda::range,nda::range, \
        V1<ComplexType,3> const&, \
        darray_t<V2<ComplexType,4>,communicator> const&, \
        darray_t<V2<ComplexType,4>,communicator>&, \
        darray_t<V2<ComplexType,4>,communicator>&); \
template void pseudopot::add_Vpp(boost::mpi3::communicator&,nda::range,nda::range, \
        V1<ComplexType,4> const&, \
        darray_t<V2<ComplexType,4>,communicator> const&, \
        darray_t<V2<ComplexType,4>,communicator>&, \
        darray_t<V2<ComplexType,4>,communicator>&); 

#define __add_hartree__(V1,V2)  \
template void pseudopot::add_Hartree(nda::range k_range,  \
        V1<ComplexType, 3> const&,  \
        darray_t<V2<ComplexType,4>,communicator> const&,  \
        darray_t<V2<ComplexType,4>,communicator>&,  \
        darray_t<V2<ComplexType,4>,communicator>&, bool);  \
template void pseudopot::add_Hartree(nda::range k_range,  \
        V1<ComplexType, 4> const&,  \
        darray_t<V2<ComplexType,4>,communicator> const&,  \
        darray_t<V2<ComplexType,4>,communicator>&,  \
        darray_t<V2<ComplexType,4>,communicator>&, bool);

#define __add_exchange__(V1,V2)  \
template void pseudopot::add_exchange(nda::range k_range,  \
        V1<ComplexType, 3> const&,  \
        darray_t<V2<ComplexType,4>,communicator> const&,  \
        darray_t<V2<ComplexType,4>,communicator>&);  \
template void pseudopot::add_exchange(nda::range k_range,  \
        V1<ComplexType, 4> const&,  \
        darray_t<V2<ComplexType,4>,communicator> const&,  \
        darray_t<V2<ComplexType,4>,communicator>&);

__add_Vpp__(host_array)
__add_Vpp2__(host_array_view,host_array)

__add_hartree__(host_array,host_array)
__add_hartree__(host_array_view,host_array)

__add_exchange__(host_array,host_array)
__add_exchange__(host_array_view,host_array)

#if defined(ENABLE_DEVICE)
using memory::device_array;
using memory::unified_array;
using memory::device_array_view;
using memory::unified_array_view;


__add_Vpp__(device_array)
__add_Vpp2__(device_array_view,device_array)
__add_hartree__(host_array,device_array)
__add_hartree__(host_array_view,device_array)
__add_hartree__(unified_array,device_array)
__add_hartree__(unified_array_view,device_array)
__add_hartree__(device_array,device_array)
__add_hartree__(device_array_view,device_array)

__add_Vpp__(unified_array)
__add_Vpp2__(unified_array_view,unified_array)
__add_hartree__(host_array,unified_array)
__add_hartree__(host_array_view,unified_array)
__add_hartree__(unified_array,unified_array)
__add_hartree__(unified_array_view,unified_array)

#endif

} // namespace hamilt


