/**
 * ==========================================================================
 * CoQuí: Correlated Quantum ínterface
 *
 * Copyright (c) 2022-2026 Simons Foundation & The CoQuí developer team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ==========================================================================
 */

#ifndef COQUI_MINIMAL_JSON_HPP
#define COQUI_MINIMAL_JSON_HPP

/**
 * TEST-ONLY minimal JSON reader.
 *
 * It exists so that unit tests can consume reference digests generated by this
 * repository's own python side (tc_validation/tests/export_tc*_reference.py)
 * WITHOUT adding a JSON dependency to the library. It is deliberately minimal:
 * it parses the subset those generators emit, it uses Catch2's REQUIRE for its
 * error handling, and nothing in src/ outside tests/ may include it.
 *
 * Introduced by increment TC-1; shared with TC-3.
 */

#include <cctype>
#include <cstdlib>
#include <fstream>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include "catch2/catch.hpp"

namespace bdft_tests {

// =======================================================================
//  A minimal JSON reader -- TEST-ONLY, and only for the file this repo's
//  own export script writes. No dependency is added to the library.
// =======================================================================
namespace mjson {

  struct Value;
  using Object = std::map<std::string, Value>;
  using Array  = std::vector<Value>;

  struct Value {
    enum kind_t { NUL, BOOL, NUM, STR, ARR, OBJ } kind = NUL;
    bool b = false;
    double num = 0.0;
    std::string str;
    std::shared_ptr<Array> arr;
    std::shared_ptr<Object> obj;

    Value const &operator[](std::string const &k) const {
      REQUIRE(kind == OBJ);
      auto it = obj->find(k);
      if (it == obj->end()) { FAIL("mjson: missing key '" << k << "'"); }
      return it->second;
    }
    Value const &operator[](std::size_t i) const {
      REQUIRE(kind == ARR);
      REQUIRE(i < arr->size());
      return (*arr)[i];
    }
    std::size_t size() const { return (kind == ARR) ? arr->size() : 0; }
    double d() const { REQUIRE(kind == NUM); return num; }
    long   i() const { REQUIRE(kind == NUM); return long(std::llround(num)); }
    std::string s() const { REQUIRE(kind == STR); return str; }
    std::vector<double> vd() const {
      REQUIRE(kind == ARR);
      std::vector<double> v;
      v.reserve(arr->size());
      for (auto const &e : *arr) v.push_back(e.d());
      return v;
    }
    std::vector<long> vi() const {
      REQUIRE(kind == ARR);
      std::vector<long> v;
      v.reserve(arr->size());
      for (auto const &e : *arr) v.push_back(e.i());
      return v;
    }
  };

  struct Parser {
    std::string const &t;
    std::size_t p = 0;
    explicit Parser(std::string const &s) : t(s) {}
    void ws() { while (p < t.size() and std::isspace((unsigned char)t[p])) ++p; }
    char peek() { ws(); return (p < t.size()) ? t[p] : '\0'; }
    Value parse() {
      ws();
      const char c = peek();
      if (c == '{') return obj();
      if (c == '[') return arr();
      if (c == '"') { Value v; v.kind = Value::STR; v.str = str(); return v; }
      if (c == 't' or c == 'f') {
        Value v; v.kind = Value::BOOL;
        v.b = (c == 't');
        p += (c == 't') ? 4 : 5;
        return v;
      }
      if (c == 'n') { p += 4; return Value{}; }
      return num();
    }
    std::string str() {
      ws();
      REQUIRE(t[p] == '"');
      ++p;
      std::string out;
      while (t[p] != '"') {
        if (t[p] == '\\') { ++p; out.push_back(t[p]); }
        else out.push_back(t[p]);
        ++p;
      }
      ++p;
      return out;
    }
    Value num() {
      ws();
      std::size_t q = p;
      while (q < t.size() and (std::isdigit((unsigned char)t[q]) or t[q] == '+' or
                               t[q] == '-' or t[q] == '.' or t[q] == 'e' or t[q] == 'E'))
        ++q;
      Value v;
      v.kind = Value::NUM;
      v.num = std::stod(t.substr(p, q - p));
      p = q;
      return v;
    }
    Value arr() {
      Value v;
      v.kind = Value::ARR;
      v.arr = std::make_shared<Array>();
      REQUIRE(peek() == '[');
      ++p;
      if (peek() == ']') { ++p; return v; }
      while (true) {
        v.arr->push_back(parse());
        const char c = peek();
        ++p;
        if (c == ']') break;
        REQUIRE(c == ',');
      }
      return v;
    }
    Value obj() {
      Value v;
      v.kind = Value::OBJ;
      v.obj = std::make_shared<Object>();
      REQUIRE(peek() == '{');
      ++p;
      if (peek() == '}') { ++p; return v; }
      while (true) {
        std::string k = str();
        REQUIRE(peek() == ':');
        ++p;
        (*v.obj)[k] = parse();
        const char c = peek();
        ++p;
        if (c == '}') break;
        REQUIRE(c == ',');
      }
      return v;
    }
  };

  inline Value load(std::string const &path) {
    std::ifstream f(path);
    REQUIRE(f.good());
    std::stringstream ss;
    ss << f.rdbuf();
    const std::string s = ss.str();
    Parser pr(s);
    return pr.parse();
  }

} // namespace mjson

} // namespace bdft_tests

#endif // COQUI_MINIMAL_JSON_HPP
